apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-lobe-chat-secrets
  labels:
    app: lobe-chat
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  openai-api-key: {{ .Values.env.OPENAI_API_KEY | b64enc }}
  access-code: {{ .Values.env.ACCESS_CODE | b64enc }}