apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lobe-chat
  labels:
    app: lobe-chat
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    app: lobe-chat
    release: {{ .Release.Name }}